### ISSUE TITLE
Docker build fails for Travis

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF-SuperBuild#331]
![image](https://user-images.githubusercontent.com/33289025/75148248-1eb04200-56f7-11ea-801b-21e4ef772cd9.png)

One of the Travis Docker build fails. I think I remember @casperdcl saying that this is to be expected, as the Docker build is only triggered for the master branch. I guess this means we need to add an `allow_failures` for this one?

**Comment by casperdcl** [comment]
AFAIK nothing should fail - if a failure is expected the test should've been skipped completely. Will have a re-look.

**Comment by rijobro** [comment]
Good spot, the actual error is that it's missing the `pip` installed `deprecation`. Sorry.

How come `deprecation` isn't available when it's in the `.travis.yml` (and all the other matrix elements are happy)?

**Comment by casperdcl** [comment]
Hmm on a realted note there are quite a few differences between SIRF and SuperBuild's travis config.

In addition to the `deprecation` and `nibabel` package installation, theres:

```yml
dist: xenial  # Ubuntu 14.04 LTS
addons:
 apt:
  packages:
  - libinsighttoolkit4-dev
```

versus

```yml
dist: bionic  # Ubuntu 18.04 LTS
addons:
 apt:
  packages:
  # dependencies for ASTRA toolbox
  - autotools-dev
  - automake
  - autogen
  - autoconf
  - libtool
```
