### ISSUE TITLE
add steps from first_run.sh to Vagrantfile?

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#740]
When creating #739, I wondered if we shouldn't put `configure_gnome.sh` and `configure_jupyter.sh` in our Vagrantfile (with a `sudo -u $SIRFUSER` or similar presumably). Would that work?

We then only need to do `zero_fill.sh` before exporting.

**Comment by KrisThielemans** [comment]
Adding configure_gnome doesn't work.
```
    default: + sudo -u sirfuser -H bash /home/sirfuser/devel/SIRF-SuperBuild/VirtualBox/scripts/configure_gnome.sh
    default: grep: /proc//environ: No such file or directory
    default: grep: /proc//environ: No such file or directory
    default:
    default: (process:19593): dconf-WARNING **: 15:38:30.670: failed to commit changes to dconf: The given address is empty
    default:
    default: (process:19596): dconf-WARNING **: 15:38:30.673: failed to commit changes to dconf: The given address is empty
    default:
    default: (process:19599): dconf-WARNING **: 15:38:30.675: failed to commit changes to dconf: The given address is empty
    default:
    default: (process:19602): dconf-WARNING **: 15:38:30.677: failed to commit changes to dconf: The given address is empty
    default:
    default: (process:19605): dconf-WARNING **: 15:38:30.680: failed to commit changes to dconf: The given address is empty
    default:
    default: (process:19608): dconf-WARNING **: 15:38:30.683: failed to commit changes to dconf: The given address is empty
    default:
    default: (process:19611): dconf-WARNING **: 15:38:30.685: failed to commit changes to dconf: The given address is empty
```
Not sure why this is
